Fix block spacing bug
Why:
Currently if a block is given just a parameter and no actual content the
formatter will return a block with an extra space, which is a rubocop
error: 'Layout/ExtraSpacing: Layout/ExtraSpacing: Unnecessary spacing
detected.'

for example: { |el| } -> { |el|  }

This commit:
Updates the block node to not add an extra space if the block has no
contents.

Co-authored-by: christoomey <chris@thoughtbot.com>
Co-authored-by: johnschoeman <johnschoeman1617@gmail.com>